# [local] generate age key from ssh:
# $ mkdir -p ~/.config/sops/age
# $ nix-shell -p ssh-to-age --run "ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt"
# [local] get public age key
# $ nix-shell -p age --run "age-keygen -y ~/.config/sops/age/keys.txt"
# Configure SOPS_AGE_KEY_FILE
# $ export SOPS_AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt"
#
# [server] get public age key from ssh key
# $ sudo nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
#
# create the encrypted secrets file
# $ nix-shell -p sops --run "sops nodes/node3/secrets/secrets.json"
# if .sops.yaml gets changed, update encrypted file(s) with new keys:
# $ nix-shell -p sops --run "sops updatekeys nodes/node3/secrets/secrets.json"
keys:
  - &local age1ucqcz2l8mnawv76ujer8k4v7pp39mg70vpudtwnyt7dc36g4te9szyrlc4
  - &node3 age10j9wyyz9a70ar75l4nd99vvpsalvvra0xg92sju3zycy5q9qjchsfna36x
creation_rules:
  - path_regex: nodes/node3/secrets/secrets.json$
    key_groups:
    - age:
      - *local
      - *node3
